import type { SimpleIcon } from "simple-icons";
import {
  siAndroid,
  siAnthropic,
  siApple,
  siApplemusic,
  siDiscord,
  siEvernote,
  siGmail,
  siGoogle,
  siGoogleassistant,
  siGooglecalendar,
  siGooglechrome,
  siGooglehome,
  siGooglenews,
  siHomeassistant,
  siLinux,
  siMessenger,
  siNotion,
  siPerplexity,
  siPhilipshue,
  siPython,
  siReddit,
  siSignal,
  siSocketdotio,
  siSoundcloud,
  siSpotify,
  siTelegram,
  siTrello,
  siWhatsapp,
  siX,
  siZapier,
} from "simple-icons";

/** Inline SVG from package (reliable, no CDN). */
export const integrationIconsInline: Record<string, SimpleIcon> = {
  whatsapp: siWhatsapp,
  telegram: siTelegram,
  discord: siDiscord,
  signal: siSignal,
  imessage: siApple,
  messenger: siMessenger,
  "google-ai": siGoogle,
  anthropic: siAnthropic,
  claude: siAnthropic,
  perplexity: siPerplexity,
  notion: siNotion,
  trello: siTrello,
  "google-calendar": siGooglecalendar,
  evernote: siEvernote,
  spotify: siSpotify,
  itunes: siApplemusic,
  soundcloud: siSoundcloud,
  "philips-hue": siPhilipshue,
  nest: siGooglehome,
  "home-assistant": siHomeassistant,
  browser: siGooglechrome,
  search: siGoogle,
  voice: siGoogleassistant,
  email: siGmail,
  webhooks: siZapier,
  python: siPython,
  realtime: siSocketdotio,
  twitter: siX,
  reddit: siReddit,
  macos: siApple,
  ios: siApple,
  android: siAndroid,
  linux: siLinux,
  "news-search": siGooglenews,
};

/**
 * CDN slug for brands not shipped in simple-icons npm (trademark removals).
 * @see https://cdn.simpleicons.org/{slug}
 */
export const integrationIconsCdnSlug: Record<string, string> = {
  slack: "slack",
  "slack-prod": "slack",
  chatgpt: "openai",
  openai: "openai",
  vision: "openai",
  teams: "microsoftteams",
  midjourney: "midjourney",
  sms: "twilio",
  "image-gen": "stabilityai",
  "pdf-search": "adobeacrobatreader",
  windows: "windows",
  "weather-bot": "openweathermap",
};
